version: "3"
services:
  app:
    image: flow
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
volumes:
  mongo:
